spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/photobook
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none

  redis:
    host: localhost
    port: 6379

logging:
  level:
    hgcq.photobook.controller: debug
    hgcq.photobook.service: debug
    root: info
  file:
    name: photobook.log
