spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mangjun
    password: audjun510
    url: jdbc:mysql://localhost:3306/photobook
#    url: jdbc:h2:tcp://localhost/~/photobook
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  redis:
    host: localhost
    port: 6379

logging:
  level:
    hgcq.photobook.controller: debug
    hgcq.photobook.service: debug
    root: info
  file:
    name: photobook.log
